language: go

go:
  - 1.x
  - master

matrix:
  allow_failures:
    - go: master
  fast_finish: true

install:
  - # nop

script:
  - go get -t -v ./...
  - go test -v -race ./...
  - diff -u <(echo -n) <(gofmt -d -s .) # check formatting
